---
title: "Data Cleaning"
author: Brenden Eum
date: July 24, 2023
output: 
  html_document: 
    theme: united
    toc: yes
    toc_float: yes
    toc_depth: 2
    number_sections: yes
    code_folding: hide
    df_print: default
---


# Preamble.

```{r}
rm(list=ls())
library(dplyr)
library(ggplot2)
library(plotrix)
library(readr)

ddmdir = "../helpers/ddm"
custdir = "../helpers/custom"
tempdir = "../outputs/temp"
figdir = "../outputs/figures"
rawdatadir = "../../data/raw_data"
datadir = "../../data/processed_data"

```

# Import plot options and useful functions.

```{r}
source(file.path(custdir, "GainLossColorPalette.R"))
source(file.path(custdir, "MyPlotOptions.R"))
source(file.path(custdir, "se.R"))
```

# Import and transform data.

```{r}
rawdata = read.csv(file.path(rawdatadir, "2023.07.26-pilot.csv"))
rawdata = rawdata[rawdata$display=="Trial" & rawdata$Screen.Name=="Choice",]
voi = c(
  "Participant.Private.ID",
  "Trial.Number",
  "Reaction.Time",
  "Response",
  "L1H",
  "L1PrH",
  "L1M",
  "L1PrM",
  "L1L",
  "L1PrL",
  "L2H",
  "L2PrH",
  "L2M",
  "L2PrM",
  "L2L",
  "L2PrL",
  "Spreadsheet.Name"
)
rawdata = rawdata[,voi]
```

# Clean data.

```{r}
# Only keep RTs in the lower 97% quantile.
rt.threshold = quantile(rawdata$Reaction.Time, probs=c(.95))
data = rawdata[rawdata$Reaction.Time<=rt.threshold,]

# RTs in secs
data$Reaction.Time = data$Reaction.Time/1000

# Choice in terms of left or right. (1=L, 0=R)
data$choice_lr = data$Response

# Turn lottery information into numeric.
data$L1H = parse_number(data$L1H)
data$L1M = parse_number(data$L1M)
data$L1L = parse_number(data$L1L)
data$L2H = parse_number(data$L2H)
data$L2M = parse_number(data$L2M)
data$L2L = parse_number(data$L2L)
data$L1PrH = parse_number(data$L1PrH)/100
data$L1PrM = parse_number(data$L1PrM)/100
data$L1PrL = parse_number(data$L1PrL)/100
data$L2PrH = parse_number(data$L2PrH)/100
data$L2PrM = parse_number(data$L2PrM)/100
data$L2PrL = parse_number(data$L2PrL)/100

# Change other variables into numeric
data$Trial.Number = as.numeric(data$Trial.Number)
data$Response = as.numeric(data$Response)

# Replace NA's with 0 since they are $0 with 0% probability.
data[is.na(data)] <- 0

# p's and r's
data$Spreadsheet.Name = parse_number(data$Spreadsheet.Name)
data$r = as.numeric(substr(toString(data$Spreadsheet.Name),1,1))/10
data$p = as.numeric(substr(toString(data$Spreadsheet.Name),2,2))/10

# Choice type
data$type = "AB"
data$type[data$Trial.Number > 20 & data$Trial.Number<=40] = "ApBp"

# Left and right mapped to A B.
data$left = "A"
data$right = "B"
data$right[data$L2H==0] = "A"
data$left[data$L2H==0] = "B"

# Choice in terms of AB (A=1, B=0)
data$choice_ab = NA
data$choice_ab[data$choice_lr==1 & data$left=="A"] = 1
data$choice_ab[data$choice_lr==0 & data$left=="A"] = 0
data$choice_ab[data$choice_lr==1 & data$left=="B"] = 0
data$choice_ab[data$choice_lr==0 & data$left=="B"] = 1

# Expected values of A and B
data$vA = NA
data$vB = NA
data$vA[data$left=="A"] = data$L1H[data$left=="A"]*data$L1PrH[data$left=="A"] + data$L1M[data$left=="A"]*data$L1PrM[data$left=="A"] + data$L1L[data$left=="A"]*data$L1PrL[data$left=="A"]
data$vA[data$left=="B"] = data$L2H[data$left=="B"]*data$L2PrH[data$left=="B"] + data$L2M[data$left=="B"]*data$L2PrM[data$left=="B"] + data$L2L[data$left=="B"]*data$L2PrL[data$left=="B"]
data$vB[data$left=="A"] = data$L2H[data$left=="A"]*data$L2PrH[data$left=="A"] + data$L2M[data$left=="A"]*data$L2PrM[data$left=="A"] + data$L2L[data$left=="A"]*data$L2PrL[data$left=="A"]
data$vB[data$left=="B"] = data$L1H[data$left=="B"]*data$L1PrH[data$left=="B"] + data$L1M[data$left=="B"]*data$L1PrM[data$left=="B"] + data$L1L[data$left=="B"]*data$L1PrL[data$left=="B"]

# H's
data$H = apply(data[,c("L1H", "L2H")], 1, max)

# Expected value difference (A-B).
data$vDiff_ab = data$vA - data$vB

# Rename columns and only keep variables of interest.
data = data %>%
  mutate(
    subject = Participant.Private.ID,
    trial = Trial.Number,
    rt = Reaction.Time
  )
voi = c(
  "subject",
  "trial",
  "type",
  "rt",
  "p",
  "r",
  "vDiff_ab",
  "choice_ab",
  "vA",
  "vB",
  "choice_lr",
  "H"
)
data = data[,voi]

summary(data)
png(file.path(figdir,'histogram_of_accepted_trials.png'))
hist(data$trial)
dev.off()
```


# Save

```{r}
save(data, file=file.path(datadir, "pilotdata.RData"))
write.csv(data, file=file.path(datadir, "pilotdata.csv"), row.names=F)
```